extends:
  import: classic
  file: go/pipeline.yaml
pipelines:
  pullRequest:
    setup:
      steps:
      - sh: go get github.com/google/uuid
        name: get-uuid
      - sh: go get -u github.com/gorilla/mux
        name: get-mux
      - sh: go get -u github.com/cweill/gotests/...
        name: get-gotests
      - sh: go get github.com/tebeka/go2xunit/...
        name: get-go2xunit
      - sh: go get github.com/securego/gosec/cmd/gosec/...
        name: get-gosec
      - sh: go get github.com/securego/gosec
        name: get-securego-gosec
    build:
      steps:
      - sh: gotests -all -w .
        name: generate-go-unit-test
      - sh: go test -v | go2xunit -output test_unit_output.xml
        name: run-go-test
      - sh: go test -coverprofile=coverage.out
        name: run-go-test-coverage
      - sh: go tool cover -func=coverage.out > test_coverage_output.out
        name: run-go-test-coverage-analysis
      - sh: gosec -include=G505 -exclude=G101,G102,G103,G104,G105,G106,G107,G201,G202,G203,G204,G301,G302,G303,G304,G305,G401,G402,G403,G404,G501,G502,G503,G504 -nosec=true -fmt=json -out=test_security_output.json .
        name: run-go-sec-test
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview

  release:
    setup:
      steps:
      - sh: go get github.com/google/uuid
        name: get-uuid
      - sh: go get -u github.com/gorilla/mux
        name: get-mux
      - sh: go get -u github.com/cweill/gotests/...
        name: get-gotests
      - sh: go get github.com/tebeka/go2xunit/...
        name: get-go2xunit
      - sh: go get github.com/securego/gosec/cmd/gosec/...
        name: get-gosec
      - sh: go get github.com/securego/gosec
        name: get-securego-gosec
    build:
      steps:
      - sh: gotests -all -w .
        name: generate-go-unit-test
      - sh: go test -v | go2xunit -output test_unit_output.xml
        name: run-go-test
      - sh: go test -coverprofile=coverage.out
        name: run-go-test-coverage
      - sh: go tool cover -func=coverage.out > test_coverage_output.out
        name: run-go-test-coverage-analysis
      - sh: gosec -include=G505 -exclude=G101,G102,G103,G104,G105,G106,G107,G201,G202,G203,G204,G301,G302,G303,G304,G305,G401,G402,G403,G404,G501,G502,G503,G504 -nosec=true -fmt=json -out=test_security_output.json .
        name: run-go-sec-test
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          name: helm-release
          sh: jx step helm release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote
